directories:
  logging: log  # Folder where the logs will be written to
  rules: rules # Folder from which the rule files will be loaded
  param: params # Folder from which the parameter files will be loaded
  config: config # Folder from which configuration files will be loaded
  lib: lib # Folder where additional libraries can be placed
location:
  latitude: 0.0 
  longitude: 0.0
  elevation: 0.0
openhab:
  connection:
    url: '' 
    user: ''
    password: ''
  general:
    listen_only: true  # If True HABApp will not change anything on the openHAB instance.
    wait_for_openhab: false # If True HABApp will wait for items from the openHAB instance before loading any rules on startup
  ping:
    enabled: true  # If enabled the configured item will show how long it takes to send an update from HABApp and get the updated value back from openhabin milliseconds
    item: HABApp_Ping # Name of the Numberitem
    interval: 10 # Seconds between two pings
